### PR TITLE
Fixed yml deprecations

### PR DESCRIPTION
**Pull request by hrba**

### CODE REVIEW

**Comment by K-Phoen** [comment]
Thanks :)

**Comment by hrba** [comment]
You welcome.

Btw, so you definitely abandoned the bundle? If so that’s pretty sad. I’ve been using it in few projects.

Best,
Wojciech

## 

Wojciech Ciolko
email: w.ciolko@gmail.com

**Comment by K-Phoen** [comment]
Yep, I've not used this bundle in years so I decided to stop maintaining it.

I can add you as a collaborator if you want :)

**Comment by hrba** [comment]
Unfortunately don’t have much time to work on it, but I’ll ping you when I’ll need it.

Best,
Wojciech

## 

Wojciech Ciolko
email: w.ciolko@gmail.com

**Pull request merged**
